name = "listapedidos-api"
main = "src/index.ts"
compatibility_date = "2026-09-29"

[vars]
ALLOWED_ORIGIN = "https://andermuchael-glitch.github.io"

[[d1_databases]]
binding = "DB"
database_name = "listapedidos"
database_id = "52b9dd7a-7684-4f55-ace7-1163598c6305"
